### ISSUE TITLE
Connections to mongodb seem to not closing properly

### ISSUE THREAD

**Issue by dpavlos** [ARGOeu/argo-web-api#137]
After a recent issue we had with the API  (the process was properly running on port 443 but it couldn't serve any request) we noticed in the MongoDB logs that the open connections were over 1K and were not closing. We tried to stop/start the api and just after this the connections dropped to 0 and the api was again functional. We suspect that connections to mongodb are not handled properly in some cases.

**Comment by makistsantekidis** [comment]
Fixed in #150
